# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# See https://www.packer.io/docs/templates/hcl_templates/blocks/packer for more info
packer {
  required_plugins {
    vagrant = {
      source  = "github.com/hashicorp/vagrant"
      version = ">= 1.1.6"
    }
    virtualbox = {
      source  = "github.com/hashicorp/virtualbox"
      version = ">= 1.1.3"
    }
  }
}

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "harddisk_size" {
  type    = string
  default = "105536"
}

variable "iso_location" {
  type    = string
  default = "/mnt/ISO"
}

variable "vm_name" {
  type    = string
  default = "ol9"
}

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "virtualbox-iso" "oraclelinux9" {
  boot_command            = ["<up><wait><tab> net.ifnames=0 biosdevname=0 text inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ol9.cfg<enter><wait>"]
  boot_wait               = "5s"
  disk_size               = "${var.harddisk_size}"
  guest_additions_path    = "/tmp/VBoxGuestAdditions_{{ .Version }}.iso"
  guest_os_type           = "Oracle_64"
  hard_drive_discard      = "true"
  hard_drive_interface    = "sata"
  hard_drive_nonrotational= "true"
  headless                = false
  http_directory          = "http"
  iso_checksum            = "MD5:02523b170e5a8a598ca7ae4c66f44e32"
  iso_url                 = "${var.iso_location}/OracleLinux-R9-U6-x86_64-dvd.iso"
  shutdown_command        = "/sbin/halt -h -p"
  ssh_password            = "vagrant"
  ssh_port                = 22
  ssh_timeout             = "10000s"
  ssh_username            = "root"
  vboxmanage              = [["modifyvm", "{{ .Name }}", "--memory", "4096"], ["modifyvm", "{{ .Name }}", "--cpus", "4"], ["modifyvm", "{{ .Name }}", "--nat-localhostreachable1", "on"]]
  virtualbox_version_file = "/tmp/.vbox_version"
  vm_name                 = "${var.vm_name}"
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.virtualbox-iso.oraclelinux9"]

  provisioner "shell" {
    script = "scripts/create_vagrant_user.sh"
  }

  provisioner "shell" {
    inline = ["dnf update -y"]
  }

  provisioner "shell" {
    expect_disconnect = true
    inline            = ["reboot"]
  }

  provisioner "shell" {
    expect_disconnect = true
    script            = "scripts/vbox_guest_additions.sh"
  }

  provisioner "shell" {
    expect_disconnect = true
    inline            = ["reboot"]
  }

  provisioner "shell" {
    pause_before = "10s"
    script       = "scripts/cleanup.sh"
    timeout      = "10s"
  }

  post-processor "vagrant" {
    compression_level = 6
    output            = "../build/${var.vm_name}-x86_64-{{ .Provider }}.box"
  }
}
